### ISSUE TITLE
4x4 Evolution DNS Issues

### ISSUE THREAD

**Issue by codepoet80** [Kazade/dreampi#3]
4x4 Evo attempts to contact one of the following servers, in apparently random order:
master.4x4evolution.com
master1.4x4evolution.com
master2.4x4evolution.com
master3.4x4evolution.com
master4.4x4evolution.com
master5.4x4evolution.com

As long as DNS is modified so that those server resolve to the same IP address (number) as dctalk.no-ip.info, you'll be able to connect. However, you can't get to a game lobby because the server at dctalk.no-ip.info will tell the game to look for lobbies at dctalk.no-ip.info (domain name), at which point the DNS in the DreamPi seems to be directing those queries to Sylverant's lobby server (67.222.144.120). See log attached.
[4x4EvoLog.txt](https://github.com/Kazade/dreampi/files/60564/4x4EvoLog.txt)

**Comment by Kazade** [comment]
Fixed in 0.99
