### ISSUE TITLE
Only one led on my DELL modem

### ISSUE THREAD

**Issue by sebsebseb1982** [Kazade/dreampi#7]
Hi,

I'm trying to connect my Dreamcast with DreamPi 1.6 but I cannot manage to do it :
I've got only one LED green on my DELL modem bought on [eBay](http://www.ebay.fr/itm/FAX-Modem-NW147-phone-line-for-Dell-Conexant-RD02-D400-External-56k-USB-Data/132014161890?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2060353.m2749.l2649).

My Dreamcast modem RJ11 goes through the PAL USB line inducer bought on [Dreamcast Live](http://www.dreamcastlive.net/shop.html).

Have you got any idea what's wrong with this ?
It seems that [I'm not the only one](https://www.reddit.com/r/dreamcast/comments/6a3sc2/dreampi_troubleshooting/) to encounter this problem.

![img_20170824_084014](https://user-images.githubusercontent.com/3707818/29653274-6ec3844c-88a9-11e7-9475-759b6d2fe436.jpg)
![img_20170824_084050](https://user-images.githubusercontent.com/3707818/29653273-6ec0a15a-88a9-11e7-8eba-edd6c037d028.jpg)
![img_20170824_084128](https://user-images.githubusercontent.com/3707818/29653272-6ec07c84-88a9-11e7-853e-d58045325501.jpg)
![img_20170824_084221](https://user-images.githubusercontent.com/3707818/29653271-6ec00e70-88a9-11e7-8585-bf794cf847fb.jpg)
![img_20170824_084230](https://user-images.githubusercontent.com/3707818/29653275-6ec48040-88a9-11e7-97ba-3f37f9c5fa27.jpg)
![img_20170824_085120](https://user-images.githubusercontent.com/3707818/29653587-ba578b50-88aa-11e7-8e45-1a8516bf8c09.jpg)

**Comment by pcwzrd13** [comment]
Have you tried rebooting a few times? There's a glitch with the Pi 3 where sometimes you won't get the second light. I think it has something to do with the Pi 3 having both Ethernet and Wi-Fi and DreamPi getting confused about what connection to use. It only seems to happen when using Ethernet though.

You might also check the firewall settings on your router. I know someone that had the same issue and it turned out that their router was blocking traffic to the Pi.

**Comment by sebsebseb1982** [comment]
Exactly !

I've disabled Wifi with [this conf](https://www.raspberrypi.org/forums/viewtopic.php?t=138610) and it works now !

Thank you.

**Comment by sebsebseb1982** [comment]
Whoops, not working anymore ... Just one led again.

`pi@dreampi ~ $ sudo ifdown wlan0` 
give
`ifdown: interface wlan0 not configured` 

WIFI seems to be disabled.

RPi3 has internet access so it's another problem :-(
Any clue ?

**Comment by pcwzrd13** [comment]
The only other thing I can think of is that maybe the Pi isn't getting sufficient power. Make sure the power supply you're using is at least 1A. If it's not that then it could still be that same bug. Just reboot a few times and you should get the second light eventually.

**Comment by sebsebseb1982** [comment]
I've got a 2.5A power supply. I've tried to reboot few times but it does not work better.

**Comment by sebsebseb1982** [comment]
Now, it works again, but I've added the second configuration in /boot/config.txt :

```
# turn wifi and bluetooth off
dtoverlay=pi3-disable-wifi
dtoverlay=pi3-disable-bt
```
